test: false
env: azure
run_name: ehr_preprocess
data_store: "researcher_data"
paths:
  output_dir: outputs/ehr_preprocess
  file_type: parquet
  dump_path: 'data-backup/SP-dumps/2024-09-10'

# filtering:
#   filter_date: '2022-01-01'

preprocessor:
  _target_: preprocessors.azure.AzurePreprocessor


# SP_concepts:
#   data_store: "researcher_data"
#   dump_path: 'data-backup/SP-dumps/2024-09-10'
#   types:
#     diagnosis:
#       filename: CPMI_Diagnoser.parquet
#       keep_cols: [CPR_hash, Diagnosekode, Diagnose, Noteret_dato]
#       dtypes: {CONCEPT: category}
#       chunksize: 10000000
#       file_type: parquet
#       fill_diags: false

register_concepts:
  data_store: "researcher_data"
  dump_path: 'FSEID'
  mapping_file: 'maskerede_data/mapping.csv'
  kontakt_file: 'kontakter.parquet'
  forloeb_file: 'forloeb.parquet'
  types:
    register_diagnosis:
      filename: diagnoser.asc
      keep_cols: [dw_ek_kontakt, diagnosekode]
      chunksize: 10000000
      file_type: parquet
      add_referral_reason: true
    register_medication: 
      filename: epikur.parquet
      keep_cols: [eksd, atc, indo, PID, vnr]
      chunksize: 10000000
      file_type: parquet
      add_symptoms: true
    register_procedures_surgical:
      filename: procedurer_kirurgi.asc
      keep_cols: [dw_ek_kontakt, procedurekode, dato_start, tidspunkt_start]
      chunksize: 10000000
      file_type: parquet
    register_procedures_non_surgical:
      filename: procedurer_andre.asc
      keep_cols: [dw_ek_kontakt, procedurekode, dato_start, tidspunkt_start]
      chunksize: 10000000
      file_type: parquet

admissions:
  data_store: "researcher_data"
  dump_path: 'data-backup/SP-dumps/2024-09-10'
  filename: CPMI_ADTHaendelser.parquet
  keep_cols: [CPR_hash, Flyt_ind, Flyt_ud, Afsnit, ADT_haendelse]
  file_type: parquet

patients_info:
  data_store: "researcher_data"
  dump_path: 'data-backup/SP-dumps/2024-09-10'
  filename: CPMI_PatientInfo.parquet
  names: [PID, BIRTHDATE, DEATHDATE, GENDER]
  usecols: [0, 1, 2, 3]
  file_type: parquet