preprocessor:
  main_folder: ../../../data/20210526
  output_dir: formatted_data
  file_type: csv

concepts:
  diagnose:
    icd:
      filename: Aktive_problemliste_diagnoser.csv
      names: [PID, CONCEPT, TIMESTAMP]

    ita_diagnosis:
      filename: ITA_ophold_og_respirator.csv
      names: [PID, CONCEPT, TIMESTAMP]
      usecols: [0, 3, 4]

    patients_and_admissions_aktions:
      filename: Patienter_og_indlaeggelser.csv
      names: [PID, ADMISSION_ID, CONCEPT, TIMESTAMP, TIMESTAMP_END]
      usecols: [0, 1, 2, 4, 5]

    patients_and_admissions_bi:
      filename: Patienter_og_indlaeggelser.csv
      names: [PID, ADMISSION_ID, CONCEPT, TIMESTAMP, TIMESTAMP_END]
      usecols: [0, 1, 3, 4, 5]

    adt_events:
      filename: ADT_haendelser.csv
      names: [PID, ADMISSION_ID, CONCEPT, TIMESTAMP]
      usecols: [0, 1, 2, 3]

    admissions_and_diagnoses:
      filename: Indlaeggelser_og_diagnoser.csv
      names: [ADMISSION_ID, CONCEPT]
      usecols: [0, 2]
      function:
        _partial_: true
        _target_: ehr_preprocess.preprocessors.computerome.ComputeromePrepocessor.update_with_admission_info
        pid: true
        timestamp: true


  medication:
    administered:
      filename: AdministreretMedicin.csv
      names: [PID, ADMISSION_ID, TIMESTAMP, CONCEPT, VALUE]
      usecols: [0, 1, 2, 3, 4]
      converters:
        CONCEPT:
          _partial_: true
          _target_: utils.utils.prepend
          prepend_token: M

    prescribed:
      filename: OrdineretMedicin.csv
      names: [PID, TIMESTAMP, TIMESTAMP_END, NAME, VALUE, CONCEPT]
      usecols: [0, 1, 2, 3, 4, 5]
      converters:
        CONCEPT:
            _partial_: true
            _target_: utils.utils.prepend
            prepend_token: M


  labtests:
    labtests:
      filename: AlleProevesvar.csv
      names: [PID, CONCEPT, TIMESTAMP, VALUE]
      usecols: [0, 1, 3, 5]

    covid_tests:
      filename: COVID.19_positive_proevesvar.csv
      names: [PID, CONCEPT, ADMISSION_ID, TIMESTAMP, VALUE]
      usecols: [0, 1, 2, 4, 6]
      converters:
        CONCEPT:
          _partial_: true
          _target_: utils.utils.prepend
          prepend_token: COVID_TEST
          slice_end: 0


  chartevents:
    vitals: 
      filename: VitaleVaerdier.csv
      names: [PID, CONCEPT, TIMESTAMP, VALUE]
      usecols: [0, 1, 2, 4]
      converters:
        CONCEPT:
            _partial_: true
            _target_: utils.utils.prepend
            prepend_token: Vitals_

  custom_events:
    ita_icu:
      filename: ITA_ophold_og_respirator.csv
      names: [PID, CONCEPT, TIMESTAMP, TIMESTAMP_END]
      usecols: [0, 3, 4, 5]
      converters:
        CONCEPT:
          _partial_: true
          _target_: utils.utils.prepend
          prepend_token: ICU
          slice_end: 0
      
    ita_respirator:
      filename: ITA_ophold_og_respirator.csv
      names: [PID, CONCEPT, TIMESTAMP, TIMESTAMP_END]
      usecols: [0, 3, 6, 7]
      converters:
        CONCEPT:
          _partial_: true
          _target_: utils.utils.prepend
          prepend_token: RESPIRATOR
          slice_end: 0

    smoker:
      filename: Tobak_og_Alkohol.csv
      names: [PID, TIMESTAMP, CONCEPT, VALUE]
      usecols: [0, 1, 2, 3]
      converters:
        CONCEPT:
          _partial_: true
          _target_: utils.utils.prepend
          prepend_token: SMOKER_

    alcohol:
      filename: Tobak_og_Alkohol.csv
      names: [PID, TIMESTAMP, CONCEPT]
      usecols: [0, 1, 4]
      converters:
          CONCEPT:
            _partial_: true
            _target_: utils.utils.prepend
            prepend_token: ALCOHOL_

    vape:
      filename: Tobak_og_Alkohol.csv
      names: [PID, TIMESTAMP, CONCEPT]
      usecols: [0, 1, 5]
      converters:
          CONCEPT:
            _partial_: true
            _target_: utils.utils.prepend
            prepend_token: VAPER_

patients_info:
  gender:
    filename: Patienter_og_Koen.csv
    names: [PID, GENDER]
    usecols: [0, 1]

  date_of_death:
    filename: Patienters_evt_doedsdato.csv
    names: [PID, DATE_OF_DEATH]
    converters:
      DATE_OF_DEATH:
        _partial_: true
        _target_: utils.utils.slice_wrapper
        slice_end: 10

  ages:
    filename: ADT_haendelser.csv
    names: [PID, ADMISSION_ID, TIMESTAMP, AGE]
    usecols: [0, 1, 3, 11]
    parse_dates: [TIMESTAMP]
    converters:
      TIMESTAMP:
        _partial_: true
        _target_: utils.utils.slice_wrapper
        slice_end: 10

    function: 
      _target_: ehr_preprocess.preprocessors.computerome.ComputeromePrepocessor.calc_birthdates
      _partial_: true

    # Used to fill nan values
    covid_tests:
      filename: COVID.19_positive_proevesvar.csv
      names: [ADMISSION_ID, TIMESTAMP]
      usecols: [2, 4]
      parse_dates: [TIMESTAMP]
      converters:
        TIMESTAMP:
          _partial_: true
          _target_: utils.utils.slice_wrapper
          slice_end: 10

# TODO: Map to something??? need TIMESTAMP
measurements:
  filename: Patienter_og_Koen.csv
  names: [PID, HEIGHT, WEIGHT, BMI]
  usecols: [0, 2, 3, 4]