preprocessor:
  main_folder: ../../../data/20210526
  output_dir: .
  columns:
    mandatory: [PID, TIMESTAMP, CONCEPT]
    optional: [ADMISSION_ID, TIMESTAMP_END, VALUE, VALUE_UNIT]
  default_value: None
  format: csv

concepts:
  icd:
    filename: Aktive_problemliste_diagnoser.csv
    names: [PID, CONCEPT, TIMESTAMP]

  atca:
    filename: AdministreretMedicin.csv
    names: [PID, ADMISSION_ID, TIMESTAMP, CONCEPT, VALUE]
    usecols: [0, 1, 2, 3, 4]
    converters:
      CONCEPT:
        _partial_: true
        _target_: utils.utils.prepend
        prepend_token: M

  atco:
    filename: OrdineretMedicin.csv
    names: [PID, TIMESTAMP, TIMESTAMP_END, VALUE, CONCEPT]
    usecols: [0, 1, 2, 4, 5]
    converters:
      CONCEPT:
          _partial_: true
          _target_: utils.utils.prepend
          prepend_token: M

  labtests:
    filename: AlleProevesvar.csv
    names: [PID, CONCEPT, TIMESTAMP, VALUE]
    usecols: [0, 1, 3, 5]
  
  vitals: 
    filename: VitaleVaerdier.csv
    names: [PID, CONCEPT, TIMESTAMP, VALUE]
    usecols: [0, 1, 2, 4]
    converters:
      CONCEPT:
          _partial_: true
          _target_: utils.utils.prepend
          prepend_token: Vitals_

  ita_diagnosis:
    filename: ITA_ophold_og_respirator.csv
    names: [PID, CONCEPT, TIMESTAMP]
    usecols: [0, 3, 4]

  ita_icu:
    filename: ITA_ophold_og_respirator.csv
    names: [PID, CONCEPT, TIMESTAMP, TIMESTAMP_END]
    usecols: [0, 3, 4, 5]
    converters:
      CONCEPT:
        _partial_: true
        _target_: utils.utils.prepend
        prepend_token: ICU
        slice_end: 0
    
  ita_respirator:
    filename: ITA_ophold_og_respirator.csv
    names: [PID, CONCEPT, TIMESTAMP, TIMESTAMP_END]
    usecols: [0, 3, 6, 7]
    converters:
      CONCEPT:
        _partial_: true
        _target_: utils.utils.prepend
        prepend_token: RESPIRATOR
        slice_end: 0

  smoker:
    filename: Tobak_og_Alkohol.csv
    names: [PID, TIMESTAMP, CONCEPT, VALUE, VALUE_UNIT]
    usecols: [0, 1, 2, 3, 4]  # We transform 4th column (Drinking) to VALUE_UNIT
    converters:
      VALUE_UNIT:
        _partial_: true
        _target_: utils.utils.prepend
        prepend_token: PacksADay
        slice_end: 0
      CONCEPT:
        partial_: true
        _target: utils.utils.prepend
        _prepend_token: Smoker_

  alcohol:
    filename: Tobak_og_Alkohol.csv
    names: [PID, TIMESTAMP, CONCEPT]
    usecols: [0, 1, 4]
    converters:
        CONCEPT:
          partial_: true
          _target: utils.utils.prepend
          _prepend_token: Alcohol_

  vape:
    filename: Tobak_og_Alkohol.csv
    names: [PID, TIMESTAMP, CONCEPT]
    usecols: [0, 1, 5]
    converters:
        CONCEPT:
          partial_: true
          _target: utils.utils.prepend
          _prepend_token: Vaper_

  patients_and_admissions_aktions:
    filename: Patienter_og_indlaeggelser.csv
    names: [PID, ADMISSION_ID, CONCEPT, TIMESTAMP, TIMESTAMP_END]
    usecols: [0, 1, 2, 4, 5]

  patients_and_admissions_bi:
    filename: Patienter_og_indlaeggelser.csv
    names: [PID, ADMISSION_ID, CONCEPT, TIMESTAMP, TIMESTAMP_END]
    usecols: [0, 1, 3, 4, 5]

# TODO: No Timestamp?
measurements:
  filename: Patienter_og_Koen.csv
  names: [PID, HEIGHT, WEIGHT, BMI]
  usecols: [0, 2, 3, 4]

# TODO: Overlap?
admissions_and_diagnoses:
  filename: Indlaeggelser_og_diagnoser.csv
  names: [ADMISSION_ID, CONCEPT]
  usecols: [0, 2]



patients_info:
  gender:
    filename: Patienter_og_Koen.csv
    names: [PID, GENDER]
    usecols: [0, 1]

  date_of_death:
    filename: Patienters_evt_doedsdato.csv
    names: [PID, DATE_OF_DEATH]

  ages:
    filename: ADT_haendelser.csv
    names: [PID, TIMESTAMP, AGE]
    usecols: [0, 3, 11]
    date_columns: [TIMESTAMP]
    converters:
      TIMESTAMP:
        _partial_: true
        _target_: utils.utils.slice_wrapper
        slice_end: 10

    covid_tests:
      filename: COVID.19_positive_proevesvar.csv
      names: [ADMISSION_ID, TIMESTAMP]
      usecols: [2, 4]
      date_columns: [TIMESTAMP]
