test: false
env: azure
run_name: normalize_labs
save_name: med_diag_lab_proc_2024
paths:
  output_dir: outputs/data
  file_path: "BREAST_CANCER/formatted_data/med_diag_lab_proc_2024"
  dist_path: "BREAST_CANCER/processed_data/labs_distribution"
  file_name: "concept.labtest.csv"
  save_name: "normed_labtest"
  file_type: csv
  
preprocessor:
  _target_: preprocessors.normaliser.Normaliser

data:
  norm_type: Min_max
  chunksize: 30000000

# data:
#   norm_type: Min_max
#   n_quantiles: 1000
#   chunksize: 30000000
