test: true
env: azure
run_name: normalise_labs
save_name: med_diag_lab_proc_2024
paths:
  output_dir: outputs/data
    
preprocessor:
  _target_: preprocessors.normaliser.Normaliser

data:
  norm_type: Min_max
  chunksize: 30000000
  data_store: "workspaceblobstore"
  file_type: csv
  save_name: "normed_labtest"
  data_path: "DEEP_FETAL/all_formatted_data_csv/concept.labtest.csv"
  dist_path: "BREAST_CANCER/processed_data/labs_distribution"

# data:
#   norm_type: Min_max
#   n_quantiles: 1000
#   chunksize: 30000000
